---
title: "Dissertation prizes • Call for submissions 2020"
date: "2020-11-12"
categories: 
  - "call"
tags: 
  - "awards"
  - "dissertations"
  - "giscience"
---

The RGS-IBG GIScience Research Group awards **two annual prizes** for the two **best postgraduate dissertations** on any issue relating to GIS/Sc, spatial analysis, spatial modelling or geocomputation (see the list of [previous winners](https://geoinfo.science/dissertation-prizes/)).

The prize for the best dissertation is £100 plus an annual RGS-IBG Postgraduate Fellowship and the runner up will receive £50 plus an annual RGS-IBG Postgraduate Fellowship. We accept nominations for Masters level dissertations of approximately 10,000 words in length, which cover significant research in one or more of the above areas. Dissertations should be of "Distinction" standard and be submitted by the student's institution (Director of Postgraduate Programme or similar) and with the student’s knowledge (ideally, cc: the student in the email nomination). 

Please submit the work in electronic form, along with a copy of the dissertation regulations to Dr Seraphim Alvanides, Northumbria University at Newcastle ([s.alvanides@northumbria.ac.uk](mailto:s.alvanides@northumbria.ac.uk)). We will only accept one entry per department of higher education institutions in the **UK** and the **Republic of Ireland** (submissions from other countries will NOT be eligible).

**Deadline: Monday 30th November 2020**
