---
title: "RGS-IBG AIC 2026 • Call for Session Sponsorship "
date: "2026-01-15"
categories: 
  - "call"
  - "events"
tags: 
  - "academia"
  - "conference"
  - "event"
  - "gis"
  - "giscience"
  - "rgs"
  - "spatial-data-science"
---

## Annual International Conference 2026

The [Geographic Information Science Research Group (GIScRG)](https://giscience-rgs.github.io/) of the RGS-IBG is glad to invite you to submit proposals for sponsorship of your [RGS-IBG Annual International Conference 2026 sessions](https://www.rgs.org/research/annual-international-conference/call-for-sessions-papers-and-posters/guidance-for-session-organisers). 

### Themes

The GIScRG welcomes sessions that focus on, but not limited to:

- Geographic information science
- **GeoAI**, including but not limited to
    - Machine learning
    - Large language models
    - Vision models
    - Multimodel models
    - Foundation models
    - Agent-based modelling
    - Information retrieval
- Reproducibility and open science
- Mapping, cartography and information visualisation
- Spatial analysis and uncertainty
- Movement analysis
- Location-based services
- Crowdsourcing, citizen science and volunteered geographic information
- Critical GIS, ethics and privacy
- **Applications**, including but not limited to
    - Environment
    - Health
    - Transportation
    - Urban analytics

### Chair's theme

Every year the AIC has a [Chair's theme](https://www.rgs.org/research/annual-international-conference/chairs-theme) which this year is **Geographies of inequalities: towards just places**. The themes are often very broad and it is **not a requirement** for your proposal to be linked to the theme. Often the links between the theme and presentations at the conference are very general. Some potential ideas from the GIScRG that relate to this theme include the topics listed below, but other ideas, topics and suggestions are very welcome.

- **Geographies of inequalities: towards just places**
    - Mapping inequalities and counter-mapping
    - Spatial analysis of inequalities
    - Geograpaphic data science for social good
    
## Sponsorship

Obtaining a group sponsorship for your session is not required, but it will connect your session to the broader GIScience community of the RGS-IBG. We will promote your session along with the other sessions we sponsor, providing your session with broader publicity. The session will be part of our AIC programme, thus avoiding overlaps with other GIScience sessions. Please note, however, that sponsorships do not include financial support, although you might be able to apply for a guest pass.

Please send the information below to _giscience.rgs \[at\] gmail.com_ before **February 6th**.

- Session title
- Session abstract (250 words)
- Session organisers’ name, affiliation and email
- Session format and how many timeslots you are requiring
- Whether you aim for a co-sponsorship with other groups
- (**No** need to include abstracts for paper contributions)

We are also open to co-sponsorships with other Research Groups.

### Timeline

- [Call of papers and sessions for the RGS-IBG Annual International Conference 2026](https://www.rgs.org/research/annual-international-conference/call-for-sessions-papers-and-posters): **now open**.
- Deadline for sponsorship applications from session organisers to GIScience RG: **February 6th**
- Decision on sponsorship applications from GIScience RG to session organisers: **February 13th**
- Deadline for submissions from session organisers to RGS: **March 6th**
